# Kindai Estimating Suite — Environment Variables
# Copy to .env and adjust values

KINDAI_DEBUG=true
KINDAI_API_HOST=0.0.0.0
KINDAI_API_PORT=8000
KINDAI_MODEL_VERSION=v1.2
KINDAI_CONFIDENCE_THRESHOLD=0.45
KINDAI_IOU_THRESHOLD=0.50
KINDAI_TRAIN_EPOCHS=10
KINDAI_TRAIN_BATCH_SIZE=16
KINDAI_AUGMENT_COUNT=5
KINDAI_OCR_LANGUAGE=eng
KINDAI_DEFAULT_SCALE_TEXT=1:100
