CREATE TABLE `email_templates` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`trade` varchar(64),
	`type` enum('quote_delivery','quote_followup','quote_reminder','quote_accepted','supplier_order') NOT NULL,
	`subject` varchar(500) NOT NULL,
	`bodyHtml` text NOT NULL,
	`isActive` boolean DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `email_templates_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `trade_profiles` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`trade` varchar(64) NOT NULL,
	`businessName` varchar(255),
	`abn` varchar(20),
	`licenseNumber` varchar(100),
	`phone` varchar(20),
	`email` varchar(320),
	`website` varchar(255),
	`address` text,
	`logoUrl` text,
	`brandColour` varchar(7) DEFAULT '#FF2D78',
	`defaultMarkup` decimal(5,2) DEFAULT '20.00',
	`defaultLabourRate` decimal(8,2),
	`defaultValidDays` int DEFAULT 30,
	`defaultTerms` text,
	`defaultState` enum('NSW','VIC','QLD','SA','WA','TAS','NT','ACT'),
	`emailFromName` varchar(255),
	`emailFromAddress` varchar(320),
	`emailSignature` text,
	`sendQuoteAutomatically` boolean DEFAULT false,
	`followUpEnabled` boolean DEFAULT true,
	`followUpDays` int DEFAULT 3,
	`reminderEnabled` boolean DEFAULT true,
	`reminderDays` int DEFAULT 7,
	`suppliers` json,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `trade_profiles_id` PRIMARY KEY(`id`)
);
