CREATE TABLE `company_profiles` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`businessName` varchar(255),
	`abn` varchar(20),
	`acn` varchar(20),
	`phone` varchar(20),
	`email` varchar(320),
	`website` varchar(255),
	`address` text,
	`suburb` varchar(100),
	`cpState` enum('NSW','VIC','QLD','SA','WA','TAS','NT','ACT'),
	`postcode` varchar(10),
	`logoUrl` text,
	`defaultExclusions` text,
	`defaultInclusions` text,
	`quoteTone` enum('professional','friendly','detailed','concise') DEFAULT 'professional',
	`paymentTerms` varchar(255) DEFAULT 'Payment within 14 days of invoice',
	`warrantyTerms` text,
	`insuranceDetails` text,
	`aiInstructions` text,
	`preferredSuppliers` json,
	`xeroTenantId` varchar(100),
	`xeroAccessToken` text,
	`xeroRefreshToken` text,
	`xeroTokenExpiresAt` bigint,
	`xeroConnectedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `company_profiles_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `estimate_corrections` (
	`id` int AUTO_INCREMENT NOT NULL,
	`estimateId` int NOT NULL,
	`lineItemId` int,
	`userId` int NOT NULL,
	`trade` varchar(64) NOT NULL,
	`correctionType` enum('quantity_change','rate_change','item_added','item_removed','description_change','unit_change','waste_change') NOT NULL,
	`fieldName` varchar(64),
	`aiValue` text,
	`humanValue` text,
	`reason` text,
	`itemDescription` varchar(500),
	`section` varchar(150),
	`category` varchar(100),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `estimate_corrections_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `job_outcomes` (
	`id` int AUTO_INCREMENT NOT NULL,
	`estimateId` int NOT NULL,
	`projectId` int NOT NULL,
	`userId` int NOT NULL,
	`trade` varchar(64) NOT NULL,
	`quotedTotal` decimal(12,2) NOT NULL,
	`quotedLabourHours` decimal(10,2),
	`quotedMaterialsCost` decimal(12,2),
	`actualTotal` decimal(12,2) NOT NULL,
	`actualLabourHours` decimal(10,2),
	`actualMaterialsCost` decimal(12,2),
	`varianceAmount` decimal(12,2),
	`variancePercent` decimal(5,2),
	`profitAmount` decimal(12,2),
	`profitPercent` decimal(5,2),
	`completionDays` int,
	`clientSatisfaction` enum('excellent','good','fair','poor'),
	`lessonsLearned` text,
	`itemVariances` json,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `job_outcomes_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `job_templates` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`trade` varchar(64) NOT NULL,
	`name` varchar(255) NOT NULL,
	`description` text,
	`lineItems` json,
	`estimatedTotal` decimal(12,2),
	`timesUsed` int DEFAULT 0,
	`isActive` boolean DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `job_templates_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `price_book_items` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`trade` varchar(64),
	`category` varchar(100) NOT NULL,
	`itemCode` varchar(50),
	`name` varchar(255) NOT NULL,
	`description` text,
	`unit` varchar(30) NOT NULL,
	`unitPrice` decimal(10,2) NOT NULL,
	`supplierName` varchar(255),
	`supplierAccountNumber` varchar(100),
	`lastUpdated` timestamp DEFAULT (now()),
	`isActive` boolean DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `price_book_items_id` PRIMARY KEY(`id`)
);
