import { useEffect } from "react";

export default function TermsOfService() {
  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  return (
    <div className="min-h-screen bg-[#0a0a0a] text-gray-200">
      {/* Header */}
      <div className="border-b border-white/10 bg-[#0f0f0f]">
        <div className="max-w-4xl mx-auto px-6 py-5 flex items-center gap-3">
          <a href="/" className="flex items-center gap-2 text-orange-400 hover:text-orange-300 transition-colors">
            <svg width="28" height="28" viewBox="0 0 40 40" fill="none">
              <rect width="40" height="40" rx="8" fill="#f97316" />
              <path d="M12 28L20 12L28 28" stroke="white" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round" />
              <path d="M15 22H25" stroke="white" strokeWidth="3" strokeLinecap="round" />
            </svg>
            <span className="font-bold text-white text-lg">Kindai</span>
          </a>
          <span className="text-white/20">/</span>
          <span className="text-white/60 text-sm">Terms of Service</span>
        </div>
      </div>

      {/* Content */}
      <div className="max-w-4xl mx-auto px-6 py-12">
        <h1 className="text-3xl font-bold text-white mb-2">Terms of Service</h1>
        <p className="text-white/40 text-sm mb-10">Last updated: April 2026</p>

        <div className="bg-orange-500/10 border border-orange-500/30 rounded-lg p-4 mb-10">
          <p className="text-orange-300 text-sm font-semibold mb-1">Important Notice</p>
          <p className="text-orange-200/80 text-sm">
            All estimates, takeoffs, and quotes generated by Kindai are AI-assisted drafts for review purposes only. They do not constitute legally binding quotes, tax invoices, or professional advice. Always review and approve AI-generated outputs before sending to clients.
          </p>
        </div>

        <div className="space-y-10 text-gray-300 leading-relaxed">

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">1. Agreement to Terms</h2>
            <p>
              These Terms of Service ("Terms") govern your access to and use of the Kindai Estimating Suite platform ("Platform") operated by Kindai Pty Ltd ("Kindai", "we", "us", or "our"), an Australian company. By accessing or using the Platform, you agree to be bound by these Terms and our Privacy Policy.
            </p>
            <p className="mt-3">
              If you are using the Platform on behalf of a business or organisation, you represent that you have authority to bind that entity to these Terms, and "you" refers to that entity.
            </p>
            <p className="mt-3">
              These Terms are governed by the laws of New South Wales, Australia. Any disputes will be subject to the exclusive jurisdiction of the courts of New South Wales.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">2. Nature of AI-Generated Outputs</h2>
            <div className="bg-white/5 rounded-lg p-5 border border-white/10 mb-4">
              <h3 className="font-semibold text-white mb-2">AI Estimates Are Drafts for Review</h3>
              <p className="text-sm text-gray-400">
                All takeoffs, materials lists, labour calculations, and quotes generated by Kindai's AI are draft outputs intended to assist qualified estimators and tradespeople. They are not legally binding quotes, tax invoices, or professional engineering or construction advice.
              </p>
            </div>
            <p className="mb-3">You acknowledge and agree that:</p>
            <ul className="list-disc list-inside space-y-2 text-gray-400 ml-2">
              <li>AI-generated estimates may contain errors, omissions, or inaccuracies</li>
              <li>You are solely responsible for reviewing, verifying, and approving all outputs before use</li>
              <li>Kindai does not guarantee the accuracy, completeness, or fitness for purpose of any AI-generated output</li>
              <li>Compliance with Australian tax law (GST), Fair Work obligations, state licensing requirements, and WHS legislation remains your responsibility</li>
              <li>Kindai's compliance prompts and pre-loaded rates are provided as starting points only and may not reflect your specific enterprise agreement, award variation, or regulatory obligation</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">3. Account Registration and Access</h2>
            <p className="mb-3">To access the Platform, you must create an account. You agree to:</p>
            <ul className="list-disc list-inside space-y-2 text-gray-400 ml-2">
              <li>Provide accurate and complete registration information</li>
              <li>Maintain the security of your account credentials</li>
              <li>Notify us immediately of any unauthorised access to your account</li>
              <li>Be responsible for all activity that occurs under your account</li>
            </ul>
            <p className="mt-3">
              We reserve the right to suspend or terminate accounts that violate these Terms, engage in fraudulent activity, or misuse the Platform.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">4. Uploaded Content and Data</h2>
            <div className="space-y-4">
              <div className="bg-white/5 rounded-lg p-4 border border-white/10">
                <h3 className="font-semibold text-white mb-1">Your Content</h3>
                <p className="text-sm text-gray-400">You retain ownership of all plans, documents, and data you upload to the Platform ("Your Content"). By uploading content, you grant Kindai a limited, non-exclusive licence to process Your Content solely for the purpose of providing the Platform's services to you.</p>
              </div>
              <div className="bg-white/5 rounded-lg p-4 border border-white/10">
                <h3 className="font-semibold text-white mb-1">No AI Training on Your Data</h3>
                <p className="text-sm text-gray-400">We do not use Your Content — including uploaded plans, job descriptions, or estimate data — to train, fine-tune, or improve AI models. Your business data is yours.</p>
              </div>
              <div className="bg-white/5 rounded-lg p-4 border border-white/10">
                <h3 className="font-semibold text-white mb-1">File Processing and Retention</h3>
                <p className="text-sm text-gray-400">Uploaded files are processed to generate your estimates and stored securely in encrypted cloud storage. You may delete your files at any time. Files associated with deleted accounts are removed within 30 days.</p>
              </div>
              <div className="bg-white/5 rounded-lg p-4 border border-white/10">
                <h3 className="font-semibold text-white mb-1">Confidential Information</h3>
                <p className="text-sm text-gray-400">We treat all uploaded plans, job data, and pricing information as confidential. We do not share your business data with third parties except as required to provide the service (e.g., cloud storage providers) or as required by law.</p>
              </div>
            </div>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">5. Subscription and Payment Terms</h2>
            <p className="mb-3">Access to the Platform is provided on a subscription basis. The following terms apply:</p>
            <ul className="list-disc list-inside space-y-2 text-gray-400 ml-2">
              <li>Subscription fees are billed in advance on a monthly or annual basis</li>
              <li>All prices are in Australian Dollars (AUD) and inclusive of GST where applicable</li>
              <li>Subscriptions automatically renew unless cancelled before the renewal date</li>
              <li>You may cancel your subscription at any time; access continues until the end of the paid period</li>
              <li>Refunds are not provided for partial subscription periods, except where required by Australian Consumer Law</li>
              <li>We reserve the right to change pricing with 30 days' notice to existing subscribers</li>
              <li>Design Partner and founding member pricing is locked in as agreed at the time of enrolment</li>
            </ul>
            <p className="mt-3">
              Payments are processed by Stripe. By providing payment details, you agree to Stripe's terms of service. We do not store your full card details.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">6. Fair Use and Acceptable Use</h2>
            <p className="mb-3">You agree not to use the Platform to:</p>
            <ul className="list-disc list-inside space-y-2 text-gray-400 ml-2">
              <li>Violate any applicable law or regulation</li>
              <li>Upload content that infringes third-party intellectual property rights</li>
              <li>Attempt to reverse-engineer, scrape, or extract data from the Platform</li>
              <li>Use automated tools to access the Platform in a manner that exceeds normal usage</li>
              <li>Share account credentials with unauthorised users</li>
              <li>Use the Platform to generate fraudulent or misleading quotes</li>
              <li>Attempt to circumvent security measures or access controls</li>
            </ul>
            <p className="mt-3">
              Enterprise and multi-user accounts are subject to the user limits specified in your subscription plan. Additional users require additional licences.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">7. Intellectual Property</h2>
            <p>
              The Kindai platform, including its software, AI models, user interface, design, branding, and documentation, is owned by Kindai Pty Ltd and protected by Australian and international intellectual property laws.
            </p>
            <p className="mt-3">
              You are granted a limited, non-exclusive, non-transferable licence to use the Platform for your internal business purposes during your subscription period. This licence does not include the right to sublicence, resell, or create derivative works based on the Platform.
            </p>
            <p className="mt-3">
              You retain all intellectual property rights in Your Content. Kindai claims no ownership over your uploaded plans, job data, or generated estimates.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">8. Limitation of Liability</h2>
            <div className="bg-white/5 rounded-lg p-5 border border-white/10 mb-4">
              <p className="text-sm text-gray-400">
                To the maximum extent permitted by law, Kindai's total liability to you for any claim arising from or related to the Platform shall not exceed the total subscription fees paid by you in the 12 months preceding the claim.
              </p>
            </div>
            <p className="mb-3">Kindai is not liable for:</p>
            <ul className="list-disc list-inside space-y-2 text-gray-400 ml-2">
              <li>Errors or inaccuracies in AI-generated estimates, takeoffs, or quotes</li>
              <li>Loss of profit, revenue, or business opportunity arising from reliance on AI outputs</li>
              <li>Regulatory non-compliance arising from use of pre-loaded rates or compliance prompts without independent verification</li>
              <li>Data loss due to circumstances beyond our reasonable control</li>
              <li>Indirect, consequential, or incidental damages of any kind</li>
            </ul>
            <p className="mt-3">
              Nothing in these Terms excludes liability that cannot be excluded under the Australian Consumer Law, including consumer guarantees.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">9. Service Availability and Changes</h2>
            <p>
              We aim to provide reliable access to the Platform but do not guarantee uninterrupted availability. We may perform maintenance, updates, or modifications to the Platform at any time. We will endeavour to provide advance notice of planned downtime.
            </p>
            <p className="mt-3">
              We reserve the right to modify, suspend, or discontinue features of the Platform with reasonable notice. Material changes to the Platform that affect your subscription will be communicated with at least 30 days' notice.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">10. Dispute Resolution</h2>
            <p>
              In the event of a dispute arising from these Terms or your use of the Platform, the parties agree to first attempt to resolve the dispute through good-faith negotiation. If the dispute cannot be resolved within 30 days, either party may refer the matter to mediation through the Australian Disputes Centre before commencing legal proceedings.
            </p>
            <p className="mt-3">
              These Terms are governed by the laws of New South Wales, Australia. Subject to the above, the parties submit to the non-exclusive jurisdiction of the courts of New South Wales.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">11. Changes to These Terms</h2>
            <p>
              We may update these Terms from time to time. We will notify you of material changes by email or by posting a notice on the Platform at least 14 days before the changes take effect. Your continued use of the Platform after changes take effect constitutes your acceptance of the updated Terms.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">12. Contact Us</h2>
            <div className="bg-white/5 rounded-lg p-5 border border-white/10">
              <p className="font-semibold text-white mb-2">Kindai Pty Ltd</p>
              <p className="text-gray-400 text-sm">Email: <a href="mailto:matt@kindaiestimator.com?subject=Legal" className="text-orange-400 hover:underline">matt@kindaiestimator.com</a></p>
              <p className="text-gray-400 text-sm mt-1">Support: <a href="mailto:matt@kindaiestimator.com" className="text-orange-400 hover:underline">matt@kindaiestimator.com</a></p>
              <p className="text-gray-400 text-sm mt-1">Website: <a href="https://kindaiestimator.com" className="text-orange-400 hover:underline">kindaiestimator.com</a></p>
            </div>
          </section>

        </div>

        {/* Footer nav */}
        <div className="mt-16 pt-8 border-t border-white/10 flex flex-wrap gap-4 text-sm text-white/40">
          <a href="/" className="hover:text-orange-400 transition-colors">Home</a>
          <a href="/privacy-policy" className="hover:text-orange-400 transition-colors">Privacy Policy</a>
          <a href="/support" className="hover:text-orange-400 transition-colors">Support</a>
          <a href="/data-deletion" className="hover:text-orange-400 transition-colors">Data Deletion</a>
          <a href="mailto:matt@kindaiestimator.com?subject=Legal" className="hover:text-orange-400 transition-colors">Contact</a>
        </div>
      </div>
    </div>
  );
}
