// ─── Complete Australian Trade List (20 Trades) ───────────────────────────────
// Based on: QBCC (QLD), NSW Fair Trading, VBA (VIC), SA CBS, WA Building & Energy
// Last updated: 2024-25

export const TRADES = [
  {
    id: "electrical",
    name: "Electrical",
    icon: "Zap",
    color: "#F59E0B",
    description: "Residential & commercial electrical, data & solar",
    unit: "points",
  },
  {
    id: "plumbing",
    name: "Plumbing & Drainage",
    icon: "Droplets",
    color: "#3B82F6",
    description: "Plumbing, drainage, gasfitting & hot water systems",
    unit: "fixtures",
  },
  {
    id: "carpentry",
    name: "Carpentry & Joinery",
    icon: "Hammer",
    color: "#92400E",
    description: "Framing, fit-out, shopfitting, doors & windows",
    unit: "lm",
  },
  {
    id: "concreting",
    name: "Concreting",
    icon: "Building2",
    color: "#6B7280",
    description: "Slabs, footings, driveways & paths",
    unit: "m³",
  },
  {
    id: "hvac",
    name: "HVAC",
    icon: "Wind",
    color: "#06B6D4",
    description: "Heating, ventilation, air conditioning & mechanical services",
    unit: "kW",
  },
  {
    id: "flooring",
    name: "Flooring",
    icon: "Grid3x3",
    color: "#8B5CF6",
    description: "Tiles, timber, carpet, vinyl & hybrid flooring",
    unit: "m²",
  },
  {
    id: "landscaping",
    name: "Landscaping & Irrigation",
    icon: "Leaf",
    color: "#10B981",
    description: "Gardens, retaining walls, outdoor spaces & irrigation",
    unit: "m²",
  },
  {
    id: "cabinetry",
    name: "Cabinet Making & Joinery",
    icon: "Package",
    color: "#0D9488",
    description: "Kitchens, commercial joinery, wardrobes, shopfitting & custom cabinetry",
    unit: "lm",
  },
  {
    id: "rendering",
    name: "Rendering & Plastering",
    icon: "Layers",
    color: "#EC4899",
    description: "Internal & external render, drywall & solid plaster",
    unit: "m²",
  },
  {
    id: "painting",
    name: "Painting & Decorating",
    icon: "Paintbrush",
    color: "#F472B6",
    description: "Interior, exterior, commercial & protective coatings",
    unit: "m²",
  },
  {
    id: "bricklaying",
    name: "Bricklaying & Blocklaying",
    icon: "Square",
    color: "#DC2626",
    description: "Brickwork, blockwork, segmental paving & stonemasonry",
    unit: "m²",
  },
  {
    id: "roofing",
    name: "Roofing",
    icon: "Home",
    color: "#7C3AED",
    description: "Roof tiling, metal roofing, roof plumbing & cladding",
    unit: "m²",
  },
  {
    id: "tiling",
    name: "Tiling",
    icon: "LayoutGrid",
    color: "#0891B2",
    description: "Wall & floor tiling, mosaics & waterproofing membranes",
    unit: "m²",
  },
  {
    id: "waterproofing",
    name: "Waterproofing",
    icon: "Droplet",
    color: "#2563EB",
    description: "Wet areas, balconies, basements & below-slab waterproofing",
    unit: "m²",
  },
  {
    id: "fire-protection",
    name: "Fire Protection",
    icon: "Flame",
    color: "#EF4444",
    description: "Sprinklers, fire alarms, passive fire & emergency lighting",
    unit: "ea",
  },
  {
    id: "glazing",
    name: "Glazing & Aluminium",
    icon: "AppWindow",
    color: "#64748B",
    description: "Windows, doors, curtain wall, shopfronts & glass",
    unit: "m²",
  },
  {
    id: "quantity-surveying",
    name: "Quantity Surveying",
    icon: "Calculator",
    color: "#059669",
    description: "Bills of quantities, cost plans, contract admin & QS reports",
    unit: "hrs",
  },
  {
    id: "demolition",
    name: "Demolition & Earthmoving",
    icon: "Shovel",
    color: "#78350F",
    description: "Demolition, earthworks, excavation, asbestos removal & site preparation",
    unit: "m\u00b3",
  },
  {
    id: "swimming-pool",
    name: "Swimming Pool Construction",
    icon: "Waves",
    color: "#0EA5E9",
    description: "Pool shell, equipment, fencing, heating & compliance",
    unit: "ea",
  },
  {
    id: "steel-fabrication",
    name: "Steel Fabrication & Structural",
    icon: "Wrench",
    color: "#374151",
    description: "Structural steel, metal fabrication & erection",
    unit: "tonne",
  },
  {
    id: "ev-charging",
    name: "EV Charging Installation & Service",
    icon: "Zap",
    color: "#22C55E",
    description: "EV charger installation, maintenance, fault diagnosis & repair — residential & commercial",
    unit: "ea",
  },
  {
    id: "gasfitting",
    name: "Gasfitting",
    icon: "Flame",
    color: "#EA580C",
    description: "Gas installation, maintenance, servicing, leak testing & compliance",
    unit: "points",
  },
] as const;

export type TradeId = (typeof TRADES)[number]["id"];

// ─── Australian States ────────────────────────────────────────────────────────
export const AU_STATES = [
  { code: "NSW", name: "New South Wales" },
  { code: "VIC", name: "Victoria" },
  { code: "QLD", name: "Queensland" },
  { code: "SA", name: "South Australia" },
  { code: "WA", name: "Western Australia" },
  { code: "TAS", name: "Tasmania" },
  { code: "NT", name: "Northern Territory" },
  { code: "ACT", name: "Australian Capital Territory" },
] as const;

export type AuState = (typeof AU_STATES)[number]["code"];

// ─── GST ──────────────────────────────────────────────────────────────────────
export const GST_RATE = 0.1; // 10%

// ─── Compliance Profiles ──────────────────────────────────────────────────────
export const COMPLIANCE_DATA: Record<
  string,
  {
    licensingBodies: Record<string, { body: string; type: string; url: string }>;
    standards: { code: string; title: string }[];
    whsNotice: string;
    quoteDisclaimer: string;
  }
> = {
  electrical: {
    licensingBodies: {
      NSW: { body: "NSW Fair Trading", type: "Electrical Contractor Licence", url: "https://www.fairtrading.nsw.gov.au/trades-and-businesses/licensing/electrical-contractor-licence" },
      VIC: { body: "Energy Safe Victoria (ESV)", type: "Electrical Contractor Licence", url: "https://www.esv.vic.gov.au/licences-and-registrations/electrical-contractors/" },
      QLD: { body: "QBCC", type: "Electrical Contractor Licence", url: "https://www.qbcc.qld.gov.au/licences/types/electrical" },
      SA: { body: "Consumer and Business Services SA", type: "Electrical Contractor Licence", url: "https://www.cbs.sa.gov.au/licences/electrical" },
      WA: { body: "Electrical Licensing Board WA", type: "Electrical Contractor Licence", url: "https://www.commerce.wa.gov.au/worksafe/electrical-licensing" },
      TAS: { body: "WorkSafe Tasmania", type: "Electrical Contractor Licence", url: "https://worksafe.tas.gov.au/topics/licensing/electrical-workers-and-contractors" },
      NT: { body: "NT WorkSafe", type: "Electrical Contractor Licence", url: "https://worksafe.nt.gov.au/licences-and-registrations/electrical" },
      ACT: { body: "Access Canberra", type: "Electrical Contractor Licence", url: "https://www.accesscanberra.act.gov.au/s/article/electrical-contractor-licence" },
    },
    standards: [
      { code: "AS/NZS 3000:2018", title: "Wiring Rules (Electrical Installations)" },
      { code: "AS/NZS 3008.1.1", title: "Electrical Installations - Selection of Cables" },
      { code: "AS/NZS 3017", title: "Electrical Installations - Verification Guidelines" },
      { code: "AS/NZS 4777", title: "Grid Connection of Energy Systems via Inverters" },
    ],
    whsNotice: "All electrical work must be performed by a licensed electrician. A Certificate of Compliance for Electrical Work (CCEW) must be issued upon completion. Ensure all WHS obligations under the Work Health and Safety Act 2011 are met.",
    quoteDisclaimer: "This estimate is prepared by a licensed electrical contractor. All work will comply with AS/NZS 3000:2018 Wiring Rules. GST of 10% is included where marked. A Certificate of Compliance for Electrical Work (CCEW) will be provided upon completion. Prices are valid for 30 days from the date of issue.",
  },
  "ev-charging": {
    licensingBodies: {
      NSW: { body: "NSW Fair Trading", type: "Electrical Contractor Licence", url: "https://www.fairtrading.nsw.gov.au/trades-and-businesses/licensing/electrical-contractor-licence" },
      VIC: { body: "Energy Safe Victoria (ESV)", type: "Electrical Contractor Licence", url: "https://www.esv.vic.gov.au/licences-and-registrations/electrical-contractors/" },
      QLD: { body: "QBCC / Electrical Safety Office", type: "Electrical Contractor Licence", url: "https://www.qbcc.qld.gov.au/licences/types/electrical" },
      SA: { body: "Consumer and Business Services SA", type: "Electrical Contractor Licence (SA limits single-phase EVSE to 20A unless smart-apply exemption)", url: "https://www.cbs.sa.gov.au/licences/electrical" },
      WA: { body: "EnergySafety WA", type: "Electrical Contractor Licence", url: "https://www.commerce.wa.gov.au/worksafe/electrical-licensing" },
      TAS: { body: "WorkSafe Tasmania", type: "Electrical Contractor Licence", url: "https://worksafe.tas.gov.au/topics/licensing/electrical-workers-and-contractors" },
      NT: { body: "NT WorkSafe", type: "Electrical Contractor Licence (NT limits single-phase EVSE to 25A)", url: "https://worksafe.nt.gov.au/licences-and-registrations/electrical" },
      ACT: { body: "Access Canberra", type: "Electrical Contractor Licence (ACT limits single-phase EVSE to 25A)", url: "https://www.accesscanberra.act.gov.au/s/article/electrical-contractor-licence" },
    },
    standards: [
      { code: "AS/NZS 3000:2018 Appendix P", title: "Wiring Rules — Dedicated circuits, RCDs, and overcurrent protection for EVSE" },
      { code: "AS/NZS 3008.1.1", title: "Selection of Cables — 6mm² minimum for 32A domestic EVSE" },
      { code: "AS/NZS 3017:2022", title: "Electrical Installations — Verification Guidelines (testing & commissioning)" },
      { code: "IEC 61851-1", title: "EV Conductive Charging Systems — General Requirements (Mode 1-4 charging)" },
      { code: "IEC 61851-23", title: "DC EV Supply Equipment — requirements for DC fast chargers" },
      { code: "AS/NZS 3820", title: "Essential Safety Requirements for Electrical Equipment (EESS/RCM compliance)" },
      { code: "AS 4777.1", title: "Grid Connection of Energy Systems — for solar/EV integration and smart charging" },
    ],
    whsNotice: "All EV charger installation and repair work must be performed by a licensed electrician. A Certificate of Compliance for Electrical Work (CCEW) must be issued upon completion. EVSE installations must comply with AS/NZS 3000:2018 Appendix P. State-specific load limits: SA/QLD max 20A single-phase (unless exemption); ACT/NT max 25A single-phase; NSW/VIC/WA/TAS permit 32A single-phase. For installations >10kW, DNSP approval may be required. IP44 minimum for outdoor installations (IP65 recommended). IK07 impact protection required for public/commercial sites.",
    quoteDisclaimer: "This estimate is prepared by a licensed electrical contractor specialising in EV charging infrastructure. All work will comply with AS/NZS 3000:2018 Wiring Rules (Appendix P) and IEC 61851 EV Charging Standards. State-specific load limits and DNSP requirements will be observed. A Certificate of Compliance for Electrical Work (CCEW) will be provided upon completion. All EV chargers supplied must carry the Regulatory Compliance Mark (RCM). Prices are valid for 30 days from the date of issue.",
  },
  gasfitting: {
    licensingBodies: {
      NSW: { body: "NSW Fair Trading", type: "Gasfitting Contractor Licence", url: "https://www.fairtrading.nsw.gov.au/trades-and-businesses/licensing/gasfitting-contractor-licence" },
      VIC: { body: "Victorian Building Authority (VBA)", type: "Gasfitting Licence", url: "https://www.vba.vic.gov.au/plumbers/licences" },
      QLD: { body: "QBCC", type: "Gasfitting Licence", url: "https://www.qbcc.qld.gov.au/licences/types/gasfitting" },
      SA: { body: "Consumer and Business Services SA", type: "Gas Fitting Contractor Licence", url: "https://www.cbs.sa.gov.au/licences/gasfitting" },
      WA: { body: "Building and Energy WA", type: "Gasfitting Permit", url: "https://www.commerce.wa.gov.au/building-and-energy/gasfitting-permits" },
      TAS: { body: "CBOS Tasmania", type: "Gasfitting Contractor Licence", url: "https://www.cbos.tas.gov.au/topics/licensing/gasfitting" },
      NT: { body: "NT WorkSafe", type: "Gasfitting Contractor Licence", url: "https://worksafe.nt.gov.au/licences-and-registrations/gasfitting" },
      ACT: { body: "Access Canberra", type: "Gasfitting Contractor Licence", url: "https://www.accesscanberra.act.gov.au/s/article/gasfitting-contractor-licence" },
    },
    standards: [
      { code: "AS/NZS 5601.1:2022", title: "Gas Installations — General Installations" },
      { code: "AS/NZS 5601.2", title: "Gas Installations — LP Gas Installations in Caravans and Boats" },
      { code: "AS 4575", title: "Gas Appliance Servicing" },
      { code: "AS 4670", title: "Commercial Catering Gas Equipment" },
      { code: "AS/NZS 5263.1.1", title: "Gas Appliances — General Requirements" },
      { code: "AS 3814", title: "Industrial and Commercial Gas-Fired Appliances" },
    ],
    whsNotice: "All gasfitting work must be performed by a licensed gasfitter. A Gas Compliance Certificate must be issued upon completion of all gas work. Gas leak testing is mandatory before commissioning and after maintenance. Carbon monoxide testing is mandatory for all enclosed gas appliances. Ensure compliance with AS/NZS 5601.1:2022 and relevant state gas safety regulations.",
    quoteDisclaimer: "This estimate is prepared by a licensed gasfitting contractor. All work will comply with AS/NZS 5601.1:2022 Gas Installations and AS 4575 Gas Appliance Servicing. GST of 10% is included where marked. A Gas Compliance Certificate will be provided upon completion. Prices are valid for 30 days from the date of issue.",
  },
  plumbing: {
    licensingBodies: {
      NSW: { body: "NSW Fair Trading", type: "Plumbing Contractor Licence", url: "https://www.fairtrading.nsw.gov.au/trades-and-businesses/licensing/plumbing-and-drainage-contractor-licence" },
      VIC: { body: "Victorian Building Authority (VBA)", type: "Plumbing Licence", url: "https://www.vba.vic.gov.au/plumbers/licences" },
      QLD: { body: "QBCC", type: "Plumbing & Drainage Licence", url: "https://www.qbcc.qld.gov.au/licences/types/plumbing-drainage" },
      SA: { body: "Consumer and Business Services SA", type: "Plumbing Contractor Licence", url: "https://www.cbs.sa.gov.au/licences/plumbing" },
      WA: { body: "Building and Energy WA", type: "Plumbing Contractor Licence", url: "https://www.commerce.wa.gov.au/building-and-energy/plumbing-licensing" },
      TAS: { body: "CBOS Tasmania", type: "Plumbing Contractor Licence", url: "https://www.cbos.tas.gov.au/topics/licensing/plumbing" },
      NT: { body: "NT WorkSafe", type: "Plumbing Contractor Licence", url: "https://worksafe.nt.gov.au/licences-and-registrations/plumbing" },
      ACT: { body: "Access Canberra", type: "Plumbing Contractor Licence", url: "https://www.accesscanberra.act.gov.au/s/article/plumbing-contractor-licence" },
    },
    standards: [
      { code: "AS/NZS 3500.1", title: "Plumbing and Drainage - Water Services" },
      { code: "AS/NZS 3500.2", title: "Plumbing and Drainage - Sanitary Plumbing and Drainage" },
      { code: "AS/NZS 3500.4", title: "Plumbing and Drainage - Heated Water Services" },
      { code: "AS 1432", title: "Copper Tubes for Plumbing, Gasfitting and Drainage" },
    ],
    whsNotice: "All plumbing work must be performed by a licensed plumber. A Certificate of Compliance must be issued for all plumbing work. Ensure compliance with the National Construction Code (NCC) and relevant state plumbing regulations.",
    quoteDisclaimer: "This estimate is prepared by a licensed plumbing contractor. All work will comply with AS/NZS 3500 series standards and the National Construction Code. GST of 10% is included where marked. A Certificate of Compliance will be provided upon completion. Prices are valid for 30 days from the date of issue.",
  },
  carpentry: {
    licensingBodies: {
      NSW: { body: "NSW Fair Trading", type: "Contractor Licence (Carpentry)", url: "https://www.fairtrading.nsw.gov.au/trades-and-businesses/licensing/contractor-licence" },
      VIC: { body: "Victorian Building Authority (VBA)", type: "Domestic Builder (Carpentry)", url: "https://www.vba.vic.gov.au/builders/registration" },
      QLD: { body: "QBCC", type: "Carpentry Licence", url: "https://www.qbcc.qld.gov.au/licences/types/carpentry" },
      SA: { body: "Consumer and Business Services SA", type: "Building Work Contractor Licence", url: "https://www.cbs.sa.gov.au/licences/building" },
      WA: { body: "Building and Energy WA", type: "Builder's Registration", url: "https://www.commerce.wa.gov.au/building-and-energy/builders-registration" },
      TAS: { body: "CBOS Tasmania", type: "Building Practitioner Registration", url: "https://www.cbos.tas.gov.au/topics/licensing/building" },
      NT: { body: "NT Building Practitioners Board", type: "Builder's Licence", url: "https://nt.gov.au/industry/construction/licences-and-registrations/building-practitioners" },
      ACT: { body: "Access Canberra", type: "Builder's Licence", url: "https://www.accesscanberra.act.gov.au/s/article/builders-licence" },
    },
    standards: [
      { code: "AS 1684", title: "Residential Timber-Framed Construction" },
      { code: "AS 4440", title: "Installation of Nailplated Timber Roof Trusses" },
      { code: "AS/NZS 1170", title: "Structural Design Actions" },
      { code: "NCC Volume 1 & 2", title: "National Construction Code" },
    ],
    whsNotice: "All carpentry work must comply with the Work Health and Safety Act 2011. Ensure proper PPE is worn at all times. Working at heights requires compliance with the Code of Practice for Managing the Risk of Falls at Workplaces.",
    quoteDisclaimer: "This estimate is prepared by a licensed building contractor. All work will comply with AS 1684 and the National Construction Code. GST of 10% is included where marked. Prices are valid for 30 days from the date of issue.",
  },
  concreting: {
    licensingBodies: {
      NSW: { body: "NSW Fair Trading", type: "Contractor Licence (Concreting)", url: "https://www.fairtrading.nsw.gov.au/trades-and-businesses/licensing/contractor-licence" },
      VIC: { body: "Victorian Building Authority (VBA)", type: "Domestic Builder (Concreting)", url: "https://www.vba.vic.gov.au/builders/registration" },
      QLD: { body: "QBCC", type: "Concreting Licence", url: "https://www.qbcc.qld.gov.au/licences/types/concreting" },
      SA: { body: "Consumer and Business Services SA", type: "Building Work Contractor Licence", url: "https://www.cbs.sa.gov.au/licences/building" },
      WA: { body: "Building and Energy WA", type: "Builder's Registration", url: "https://www.commerce.wa.gov.au/building-and-energy/builders-registration" },
      TAS: { body: "CBOS Tasmania", type: "Building Practitioner Registration", url: "https://www.cbos.tas.gov.au/topics/licensing/building" },
      NT: { body: "NT Building Practitioners Board", type: "Builder's Licence", url: "https://nt.gov.au/industry/construction/licences-and-registrations/building-practitioners" },
      ACT: { body: "Access Canberra", type: "Builder's Licence", url: "https://www.accesscanberra.act.gov.au/s/article/builders-licence" },
    },
    standards: [
      { code: "AS 3600:2018", title: "Concrete Structures" },
      { code: "AS 3610", title: "Formwork for Concrete" },
      { code: "AS 1379", title: "Specification and Supply of Concrete" },
      { code: "AS/NZS 4671", title: "Steel Reinforcing Materials" },
    ],
    whsNotice: "Concreting work must comply with WHS regulations. Manual handling of concrete bags requires proper technique. Wet concrete is a skin and eye irritant — appropriate PPE must be worn. Excavation work requires a safe work method statement (SWMS).",
    quoteDisclaimer: "This estimate is prepared by a licensed concreting contractor. All work will comply with AS 3600:2018 and relevant Australian Standards. GST of 10% is included where marked. Prices are valid for 30 days from the date of issue.",
  },
  hvac: {
    licensingBodies: {
      NSW: { body: "NSW Fair Trading", type: "Refrigeration & Air Conditioning Licence", url: "https://www.fairtrading.nsw.gov.au/trades-and-businesses/licensing" },
      VIC: { body: "Victorian Building Authority (VBA)", type: "Plumbing Licence (Mechanical Services)", url: "https://www.vba.vic.gov.au/plumbers/licences" },
      QLD: { body: "QBCC", type: "Mechanical Services — Air-Conditioning & Refrigeration Licence", url: "https://www.qbcc.qld.gov.au/licences/types/air-conditioning-refrigeration" },
      SA: { body: "Consumer and Business Services SA", type: "Refrigeration & Air Conditioning Licence", url: "https://www.cbs.sa.gov.au/licences" },
      WA: { body: "Building and Energy WA", type: "Refrigeration & Air Conditioning Licence", url: "https://www.commerce.wa.gov.au/building-and-energy" },
      TAS: { body: "CBOS Tasmania", type: "Building Practitioner Registration", url: "https://www.cbos.tas.gov.au/topics/licensing/building" },
      NT: { body: "NT WorkSafe", type: "Refrigeration & Air Conditioning Licence", url: "https://worksafe.nt.gov.au" },
      ACT: { body: "Access Canberra", type: "Refrigeration & Air Conditioning Licence", url: "https://www.accesscanberra.act.gov.au" },
    },
    standards: [
      { code: "AS/NZS 1668.1", title: "The Use of Ventilation and Airconditioning in Buildings" },
      { code: "AS/NZS 3000:2018", title: "Wiring Rules (for electrical components)" },
      { code: "AS 1677", title: "Refrigerating Systems" },
      { code: "NCC Section J", title: "Energy Efficiency Requirements" },
    ],
    whsNotice: "HVAC installation must be performed by a licensed refrigeration and air conditioning mechanic. Handling refrigerants requires an ARCtick licence. All electrical connections must be made by a licensed electrician. Ensure compliance with WHS regulations when working at heights.",
    quoteDisclaimer: "This estimate is prepared by a licensed HVAC contractor. All work will comply with AS/NZS 1668 and the National Construction Code Section J. GST of 10% is included where marked. Prices are valid for 30 days from the date of issue.",
  },
  flooring: {
    licensingBodies: {
      NSW: { body: "NSW Fair Trading", type: "Contractor Licence (Flooring)", url: "https://www.fairtrading.nsw.gov.au/trades-and-businesses/licensing/contractor-licence" },
      VIC: { body: "Victorian Building Authority (VBA)", type: "Domestic Builder (Flooring)", url: "https://www.vba.vic.gov.au/builders/registration" },
      QLD: { body: "QBCC", type: "Floor Finishing and Covering Licence", url: "https://www.qbcc.qld.gov.au/licences/types/floor-finishing" },
      SA: { body: "Consumer and Business Services SA", type: "Building Work Contractor Licence", url: "https://www.cbs.sa.gov.au/licences/building" },
      WA: { body: "Building and Energy WA", type: "Builder's Registration", url: "https://www.commerce.wa.gov.au/building-and-energy/builders-registration" },
      TAS: { body: "CBOS Tasmania", type: "Building Practitioner Registration", url: "https://www.cbos.tas.gov.au/topics/licensing/building" },
      NT: { body: "NT Building Practitioners Board", type: "Builder's Licence", url: "https://nt.gov.au/industry/construction/licences-and-registrations/building-practitioners" },
      ACT: { body: "Access Canberra", type: "Builder's Licence", url: "https://www.accesscanberra.act.gov.au/s/article/builders-licence" },
    },
    standards: [
      { code: "AS 1884", title: "Floor Coverings - Resilient Sheet and Tiles" },
      { code: "AS 1288", title: "Glass in Buildings - Selection and Installation" },
      { code: "AS 4586", title: "Slip Resistance Classification of New Pedestrian Surface Materials" },
      { code: "FCAA Standards", title: "Floor Covering Association of Australasia Standards" },
    ],
    whsNotice: "Flooring installation must comply with WHS regulations. Use of adhesives and solvents requires adequate ventilation and appropriate PPE. Ensure subfloor conditions are assessed before installation to prevent trip hazards.",
    quoteDisclaimer: "This estimate is prepared by a licensed flooring contractor. All work will comply with relevant Australian Standards and manufacturer specifications. GST of 10% is included where marked. Prices are valid for 30 days from the date of issue.",
  },
  landscaping: {
    licensingBodies: {
      NSW: { body: "NSW Fair Trading", type: "Contractor Licence (Structural Landscaping)", url: "https://www.fairtrading.nsw.gov.au/trades-and-businesses/licensing/contractor-licence" },
      VIC: { body: "Victorian Building Authority (VBA)", type: "Domestic Builder (Landscaping)", url: "https://www.vba.vic.gov.au/builders/registration" },
      QLD: { body: "QBCC", type: "Structural Landscaping Licence", url: "https://www.qbcc.qld.gov.au/licences/types/structural-landscaping" },
      SA: { body: "Consumer and Business Services SA", type: "Building Work Contractor Licence", url: "https://www.cbs.sa.gov.au/licences/building" },
      WA: { body: "Building and Energy WA", type: "Builder's Registration (Structural Landscaping)", url: "https://www.commerce.wa.gov.au/building-and-energy/builders-registration" },
      TAS: { body: "CBOS Tasmania", type: "Building Practitioner Registration", url: "https://www.cbos.tas.gov.au/topics/licensing/building" },
      NT: { body: "NT Building Practitioners Board", type: "Builder's Licence", url: "https://nt.gov.au/industry/construction/licences-and-registrations/building-practitioners" },
      ACT: { body: "Access Canberra", type: "Builder's Licence", url: "https://www.accesscanberra.act.gov.au/s/article/builders-licence" },
    },
    standards: [
      { code: "AS 4419", title: "Soils for Landscaping and Garden Use" },
      { code: "AS 3500.1", title: "Plumbing and Drainage (for irrigation connections)" },
      { code: "AS 4678", title: "Earth-Retaining Structures" },
      { code: "NCC Volume 2", title: "National Construction Code (for structural elements)" },
    ],
    whsNotice: "Landscaping work must comply with WHS regulations. Excavation near underground services requires Dial Before You Dig notification. Working with chemicals (herbicides, fertilisers) requires appropriate PPE and safe handling procedures.",
    quoteDisclaimer: "This estimate is prepared by a licensed landscaping contractor. All structural work will comply with relevant Australian Standards and the National Construction Code. GST of 10% is included where marked. Prices are valid for 30 days from the date of issue.",
  },
  cabinetry: {
    licensingBodies: {
      NSW: { body: "NSW Fair Trading", type: "Contractor Licence (Cabinetmaking)", url: "https://www.fairtrading.nsw.gov.au/trades-and-businesses/licensing/contractor-licence" },
      VIC: { body: "Victorian Building Authority (VBA)", type: "Domestic Builder (Cabinetmaking)", url: "https://www.vba.vic.gov.au/builders/registration" },
      QLD: { body: "QBCC", type: "Cabinet Making Licence", url: "https://www.qbcc.qld.gov.au/licences/types/cabinet-making" },
      SA: { body: "Consumer and Business Services SA", type: "Building Work Contractor Licence", url: "https://www.cbs.sa.gov.au/licences/building" },
      WA: { body: "Building and Energy WA", type: "Builder's Registration", url: "https://www.commerce.wa.gov.au/building-and-energy/builders-registration" },
      TAS: { body: "CBOS Tasmania", type: "Building Practitioner Registration", url: "https://www.cbos.tas.gov.au/topics/licensing/building" },
      NT: { body: "NT Building Practitioners Board", type: "Builder's Licence", url: "https://nt.gov.au/industry/construction/licences-and-registrations/building-practitioners" },
      ACT: { body: "Access Canberra", type: "Builder's Licence", url: "https://www.accesscanberra.act.gov.au/s/article/builders-licence" },
    },
    standards: [
      { code: "AS/NZS 4386.1", title: "Domestic Kitchen Assemblies - Materials and Construction" },
      { code: "AS/NZS 4386.2", title: "Domestic Kitchen Assemblies - Performance Requirements" },
      { code: "AS 4084", title: "Steel Storage Racking" },
      { code: "AWISA Standards", title: "Australian Woodworking Industry Suppliers Association Standards" },
    ],
    whsNotice: "Cabinetry and joinery installation must comply with WHS regulations. Use of CNC and power tools requires appropriate training and PPE. Dust extraction is mandatory when machining MDF. Ensure adequate ventilation when applying finishes.",
    quoteDisclaimer: "This estimate is prepared by a licensed cabinetmaking and joinery contractor. All work will comply with AS/NZS 4386 kitchen assembly standards and AWISA standards. GST of 10% is included where marked. Prices are valid for 30 days from the date of issue.",
  },
  rendering: {
    licensingBodies: {
      NSW: { body: "NSW Fair Trading", type: "Contractor Licence (Plastering)", url: "https://www.fairtrading.nsw.gov.au/trades-and-businesses/licensing/contractor-licence" },
      VIC: { body: "Victorian Building Authority (VBA)", type: "Domestic Builder (Plastering)", url: "https://www.vba.vic.gov.au/builders/registration" },
      QLD: { body: "QBCC", type: "Plastering Solid Licence", url: "https://www.qbcc.qld.gov.au/licences/types/plastering" },
      SA: { body: "Consumer and Business Services SA", type: "Building Work Contractor Licence", url: "https://www.cbs.sa.gov.au/licences/building" },
      WA: { body: "Building and Energy WA", type: "Builder's Registration", url: "https://www.commerce.wa.gov.au/building-and-energy/builders-registration" },
      TAS: { body: "CBOS Tasmania", type: "Building Practitioner Registration", url: "https://www.cbos.tas.gov.au/topics/licensing/building" },
      NT: { body: "NT Building Practitioners Board", type: "Builder's Licence", url: "https://nt.gov.au/industry/construction/licences-and-registrations/building-practitioners" },
      ACT: { body: "Access Canberra", type: "Builder's Licence", url: "https://www.accesscanberra.act.gov.au/s/article/builders-licence" },
    },
    standards: [
      { code: "AS 3740", title: "Waterproofing of Domestic Wet Areas" },
      { code: "AS 2589", title: "Gypsum Linings - Application and Finishing" },
      { code: "AS 3958.1", title: "Ceramic Tiles - Guide to the Installation of Ceramic Tiles" },
      { code: "NCC Section F", title: "Health and Amenity Requirements" },
    ],
    whsNotice: "Rendering and plastering work must comply with WHS regulations. Cement and lime products are skin and eye irritants — appropriate PPE must be worn. Scaffolding for external rendering must comply with the Code of Practice for Scaffolding.",
    quoteDisclaimer: "This estimate is prepared by a licensed plastering/rendering contractor. All work will comply with relevant Australian Standards. GST of 10% is included where marked. Prices are valid for 30 days from the date of issue.",
  },
  painting: {
    licensingBodies: {
      NSW: { body: "NSW Fair Trading", type: "Contractor Licence (Decorating/Painting)", url: "https://www.fairtrading.nsw.gov.au/trades-and-businesses/licensing/contractor-licence" },
      VIC: { body: "Victorian Building Authority (VBA)", type: "Domestic Builder (Painting)", url: "https://www.vba.vic.gov.au/builders/registration" },
      QLD: { body: "QBCC", type: "Painting & Decorating Licence", url: "https://www.qbcc.qld.gov.au/licences/types/painting-decorating" },
      SA: { body: "Consumer and Business Services SA", type: "Building Work Contractor Licence", url: "https://www.cbs.sa.gov.au/licences/building" },
      WA: { body: "Building and Energy WA", type: "Builder's Registration", url: "https://www.commerce.wa.gov.au/building-and-energy/builders-registration" },
      TAS: { body: "CBOS Tasmania", type: "Building Practitioner Registration", url: "https://www.cbos.tas.gov.au/topics/licensing/building" },
      NT: { body: "NT Building Practitioners Board", type: "Builder's Licence", url: "https://nt.gov.au/industry/construction/licences-and-registrations/building-practitioners" },
      ACT: { body: "Access Canberra", type: "Builder's Licence", url: "https://www.accesscanberra.act.gov.au/s/article/builders-licence" },
    },
    standards: [
      { code: "AS/NZS 2311", title: "Guide to the Painting of Buildings" },
      { code: "AS/NZS 4506", title: "Thermosetting Powder Coating for Architectural Applications" },
      { code: "AS 4049", title: "Paints and Related Materials - Waterborne Paints" },
      { code: "Safe Work Australia", title: "Code of Practice: Managing Risks of Hazardous Chemicals" },
    ],
    whsNotice: "Painting work must comply with WHS regulations. Lead paint testing is required on pre-1970 buildings. Solvents and thinners require adequate ventilation and appropriate PPE. Working at heights requires compliance with the Code of Practice for Managing the Risk of Falls.",
    quoteDisclaimer: "This estimate is prepared by a licensed painting and decorating contractor. All work will comply with AS/NZS 2311 and relevant Australian Standards. GST of 10% is included where marked. Prices are valid for 30 days from the date of issue.",
  },
  bricklaying: {
    licensingBodies: {
      NSW: { body: "NSW Fair Trading", type: "Contractor Licence (Bricklaying)", url: "https://www.fairtrading.nsw.gov.au/trades-and-businesses/licensing/contractor-licence" },
      VIC: { body: "Victorian Building Authority (VBA)", type: "Domestic Builder (Bricklaying)", url: "https://www.vba.vic.gov.au/builders/registration" },
      QLD: { body: "QBCC", type: "Bricklaying and Blocklaying Licence", url: "https://www.qbcc.qld.gov.au/licences/types/bricklaying" },
      SA: { body: "Consumer and Business Services SA", type: "Building Work Contractor Licence", url: "https://www.cbs.sa.gov.au/licences/building" },
      WA: { body: "Building and Energy WA", type: "Builder's Registration", url: "https://www.commerce.wa.gov.au/building-and-energy/builders-registration" },
      TAS: { body: "CBOS Tasmania", type: "Building Practitioner Registration", url: "https://www.cbos.tas.gov.au/topics/licensing/building" },
      NT: { body: "NT Building Practitioners Board", type: "Builder's Licence", url: "https://nt.gov.au/industry/construction/licences-and-registrations/building-practitioners" },
      ACT: { body: "Access Canberra", type: "Builder's Licence", url: "https://www.accesscanberra.act.gov.au/s/article/builders-licence" },
    },
    standards: [
      { code: "AS 3700:2018", title: "Masonry Structures" },
      { code: "AS 4773", title: "Masonry in Small Buildings" },
      { code: "AS 3958.1", title: "Ceramic Tiles - Guide to Installation" },
      { code: "NCC Volume 1 & 2", title: "National Construction Code" },
    ],
    whsNotice: "Bricklaying work must comply with WHS regulations. Manual handling of bricks and blocks requires proper technique to prevent musculoskeletal injuries. Scaffolding must comply with the Code of Practice for Scaffolding. Silica dust from cutting masonry requires appropriate respiratory protection.",
    quoteDisclaimer: "This estimate is prepared by a licensed bricklaying contractor. All work will comply with AS 3700:2018 Masonry Structures and the National Construction Code. GST of 10% is included where marked. Prices are valid for 30 days from the date of issue.",
  },
  roofing: {
    licensingBodies: {
      NSW: { body: "NSW Fair Trading", type: "Contractor Licence (Roof Tiling/Roof Plumbing)", url: "https://www.fairtrading.nsw.gov.au/trades-and-businesses/licensing/contractor-licence" },
      VIC: { body: "Victorian Building Authority (VBA)", type: "Plumbing Licence (Roof Plumbing) / Domestic Builder (Roof Tiling)", url: "https://www.vba.vic.gov.au" },
      QLD: { body: "QBCC", type: "Roof Tiling / Roof and Wall Cladding Licence", url: "https://www.qbcc.qld.gov.au/licences/types/roof-tiling" },
      SA: { body: "Consumer and Business Services SA", type: "Building Work Contractor Licence", url: "https://www.cbs.sa.gov.au/licences/building" },
      WA: { body: "Building and Energy WA", type: "Builder's Registration", url: "https://www.commerce.wa.gov.au/building-and-energy/builders-registration" },
      TAS: { body: "CBOS Tasmania", type: "Building Practitioner Registration", url: "https://www.cbos.tas.gov.au/topics/licensing/building" },
      NT: { body: "NT Building Practitioners Board", type: "Builder's Licence", url: "https://nt.gov.au/industry/construction/licences-and-registrations/building-practitioners" },
      ACT: { body: "Access Canberra", type: "Builder's Licence", url: "https://www.accesscanberra.act.gov.au/s/article/builders-licence" },
    },
    standards: [
      { code: "AS 4055", title: "Wind Loads for Housing" },
      { code: "AS 4440", title: "Installation of Nailplated Timber Roof Trusses" },
      { code: "AS 3500.3", title: "Plumbing and Drainage - Stormwater Drainage" },
      { code: "NCC Volume 2", title: "National Construction Code" },
    ],
    whsNotice: "Roofing work must comply with WHS regulations. Working at heights is a high-risk activity — a Safe Work Method Statement (SWMS) is mandatory. All workers must use appropriate fall protection systems. Asbestos testing is required on pre-1990 roofs before any removal work.",
    quoteDisclaimer: "This estimate is prepared by a licensed roofing contractor. All work will comply with AS 4055 Wind Loads and the National Construction Code. GST of 10% is included where marked. Prices are valid for 30 days from the date of issue.",
  },
  tiling: {
    licensingBodies: {
      NSW: { body: "NSW Fair Trading", type: "Contractor Licence (Wall & Floor Tiling)", url: "https://www.fairtrading.nsw.gov.au/trades-and-businesses/licensing/contractor-licence" },
      VIC: { body: "Victorian Building Authority (VBA)", type: "Domestic Builder (Tiling)", url: "https://www.vba.vic.gov.au/builders/registration" },
      QLD: { body: "QBCC", type: "Wall and Floor Tiling Licence", url: "https://www.qbcc.qld.gov.au/licences/types/wall-floor-tiling" },
      SA: { body: "Consumer and Business Services SA", type: "Building Work Contractor Licence", url: "https://www.cbs.sa.gov.au/licences/building" },
      WA: { body: "Building and Energy WA", type: "Builder's Registration", url: "https://www.commerce.wa.gov.au/building-and-energy/builders-registration" },
      TAS: { body: "CBOS Tasmania", type: "Building Practitioner Registration", url: "https://www.cbos.tas.gov.au/topics/licensing/building" },
      NT: { body: "NT Building Practitioners Board", type: "Builder's Licence", url: "https://nt.gov.au/industry/construction/licences-and-registrations/building-practitioners" },
      ACT: { body: "Access Canberra", type: "Builder's Licence", url: "https://www.accesscanberra.act.gov.au/s/article/builders-licence" },
    },
    standards: [
      { code: "AS 3958.1", title: "Ceramic Tiles - Guide to the Installation of Ceramic Tiles" },
      { code: "AS 3958.2", title: "Ceramic Tiles - Guide to the Selection of a Tile Installation System" },
      { code: "AS 3740", title: "Waterproofing of Domestic Wet Areas" },
      { code: "AS 4586", title: "Slip Resistance Classification of New Pedestrian Surface Materials" },
    ],
    whsNotice: "Tiling work must comply with WHS regulations. Cutting tiles generates silica dust — appropriate respiratory protection is mandatory. Wet areas must be waterproofed to AS 3740 before tiling. Ensure subfloor is structurally sound before installation.",
    quoteDisclaimer: "This estimate is prepared by a licensed tiling contractor. All work will comply with AS 3958 and relevant Australian Standards. GST of 10% is included where marked. Prices are valid for 30 days from the date of issue.",
  },
  waterproofing: {
    licensingBodies: {
      NSW: { body: "NSW Fair Trading", type: "Contractor Licence (Waterproofing)", url: "https://www.fairtrading.nsw.gov.au/trades-and-businesses/licensing/contractor-licence" },
      VIC: { body: "Victorian Building Authority (VBA)", type: "Domestic Builder (Waterproofing)", url: "https://www.vba.vic.gov.au/builders/registration" },
      QLD: { body: "QBCC", type: "Waterproofing Licence", url: "https://www.qbcc.qld.gov.au/licences/types/waterproofing" },
      SA: { body: "Consumer and Business Services SA", type: "Building Work Contractor Licence", url: "https://www.cbs.sa.gov.au/licences/building" },
      WA: { body: "Building and Energy WA", type: "Builder's Registration", url: "https://www.commerce.wa.gov.au/building-and-energy/builders-registration" },
      TAS: { body: "CBOS Tasmania", type: "Building Practitioner Registration", url: "https://www.cbos.tas.gov.au/topics/licensing/building" },
      NT: { body: "NT Building Practitioners Board", type: "Builder's Licence", url: "https://nt.gov.au/industry/construction/licences-and-registrations/building-practitioners" },
      ACT: { body: "Access Canberra", type: "Builder's Licence", url: "https://www.accesscanberra.act.gov.au/s/article/builders-licence" },
    },
    standards: [
      { code: "AS 3740", title: "Waterproofing of Domestic Wet Areas" },
      { code: "AS 4654.1", title: "Waterproofing Membranes for External Above-Ground Use" },
      { code: "AS 4654.2", title: "Waterproofing Membranes - Design and Installation" },
      { code: "NCC Section F", title: "Health and Amenity Requirements" },
    ],
    whsNotice: "Waterproofing work must comply with WHS regulations. Membrane products contain solvents — adequate ventilation and appropriate PPE are mandatory. Confined space entry procedures apply for below-slab and basement waterproofing.",
    quoteDisclaimer: "This estimate is prepared by a licensed waterproofing contractor. All work will comply with AS 3740 and AS 4654 waterproofing standards. GST of 10% is included where marked. Prices are valid for 30 days from the date of issue.",
  },
  "fire-protection": {
    licensingBodies: {
      NSW: { body: "NSW Fair Trading / Fire & Rescue NSW", type: "Fire Protection Contractor Licence", url: "https://www.fairtrading.nsw.gov.au/trades-and-businesses/licensing" },
      VIC: { body: "Victorian Building Authority (VBA)", type: "Building Practitioner (Fire Protection)", url: "https://www.vba.vic.gov.au/builders/registration" },
      QLD: { body: "QBCC", type: "Fire Protection Licence (various classes)", url: "https://www.qbcc.qld.gov.au/licences/types/fire-protection" },
      SA: { body: "Consumer and Business Services SA", type: "Fire Protection Contractor Licence", url: "https://www.cbs.sa.gov.au/licences" },
      WA: { body: "Building and Energy WA", type: "Fire Protection Contractor Licence", url: "https://www.commerce.wa.gov.au/building-and-energy" },
      TAS: { body: "CBOS Tasmania", type: "Building Practitioner Registration", url: "https://www.cbos.tas.gov.au/topics/licensing/building" },
      NT: { body: "NT Building Practitioners Board", type: "Builder's Licence", url: "https://nt.gov.au/industry/construction/licences-and-registrations/building-practitioners" },
      ACT: { body: "Access Canberra", type: "Fire Protection Contractor Licence", url: "https://www.accesscanberra.act.gov.au" },
    },
    standards: [
      { code: "AS 1851", title: "Routine Service of Fire Protection Systems and Equipment" },
      { code: "AS 2118", title: "Automatic Fire Sprinkler Systems" },
      { code: "AS 1670", title: "Fire Detection, Warning, Control and Intercom Systems" },
      { code: "NCC Section E", title: "Services and Equipment (Fire Safety)" },
    ],
    whsNotice: "Fire protection work must comply with WHS regulations and the National Construction Code Section E. All fire systems must be installed, tested and commissioned by a licensed fire protection contractor. Annual service and maintenance is required under AS 1851.",
    quoteDisclaimer: "This estimate is prepared by a licensed fire protection contractor. All work will comply with AS 1851, AS 2118, AS 1670 and the National Construction Code. GST of 10% is included where marked. Prices are valid for 30 days from the date of issue.",
  },
  glazing: {
    licensingBodies: {
      NSW: { body: "NSW Fair Trading", type: "Contractor Licence (Glazing)", url: "https://www.fairtrading.nsw.gov.au/trades-and-businesses/licensing/contractor-licence" },
      VIC: { body: "Victorian Building Authority (VBA)", type: "Domestic Builder (Glazing)", url: "https://www.vba.vic.gov.au/builders/registration" },
      QLD: { body: "QBCC", type: "Glass, Glazing & Aluminium Licence", url: "https://www.qbcc.qld.gov.au/licences/types/glazing" },
      SA: { body: "Consumer and Business Services SA", type: "Building Work Contractor Licence", url: "https://www.cbs.sa.gov.au/licences/building" },
      WA: { body: "Building and Energy WA", type: "Builder's Registration", url: "https://www.commerce.wa.gov.au/building-and-energy/builders-registration" },
      TAS: { body: "CBOS Tasmania", type: "Building Practitioner Registration", url: "https://www.cbos.tas.gov.au/topics/licensing/building" },
      NT: { body: "NT Building Practitioners Board", type: "Builder's Licence", url: "https://nt.gov.au/industry/construction/licences-and-registrations/building-practitioners" },
      ACT: { body: "Access Canberra", type: "Builder's Licence", url: "https://www.accesscanberra.act.gov.au/s/article/builders-licence" },
    },
    standards: [
      { code: "AS 1288", title: "Glass in Buildings - Selection and Installation" },
      { code: "AS 2047", title: "Windows and External Glazed Doors in Buildings" },
      { code: "AS 1170.2", title: "Structural Design Actions - Wind Actions" },
      { code: "NCC Section J", title: "Energy Efficiency (glazing performance)" },
    ],
    whsNotice: "Glazing work must comply with WHS regulations. Handling large glass panels requires appropriate PPE including cut-resistant gloves. Safety glass (toughened or laminated) must be used in all hazardous locations per AS 1288. Working at heights requires fall protection.",
    quoteDisclaimer: "This estimate is prepared by a licensed glazing and aluminium contractor. All work will comply with AS 1288, AS 2047 and the National Construction Code. GST of 10% is included where marked. Prices are valid for 30 days from the date of issue.",
  },
  "quantity-surveying": {
    licensingBodies: {
      NSW: { body: "AIQS (Australian Institute of Quantity Surveyors)", type: "Certified Quantity Surveyor (CQS)", url: "https://www.aiqs.com.au/membership/member-grades" },
      VIC: { body: "Victorian Building Authority (VBA) + AIQS", type: "Quantity Surveyor Registration + CQS", url: "https://www.vba.vic.gov.au/registration-and-licensing/building-practitioner-registration/quantity-surveyor" },
      QLD: { body: "AIQS", type: "Certified Quantity Surveyor (CQS)", url: "https://www.aiqs.com.au" },
      SA: { body: "AIQS", type: "Certified Quantity Surveyor (CQS)", url: "https://www.aiqs.com.au" },
      WA: { body: "AIQS", type: "Certified Quantity Surveyor (CQS)", url: "https://www.aiqs.com.au" },
      TAS: { body: "AIQS", type: "Certified Quantity Surveyor (CQS)", url: "https://www.aiqs.com.au" },
      NT: { body: "AIQS", type: "Certified Quantity Surveyor (CQS)", url: "https://www.aiqs.com.au" },
      ACT: { body: "AIQS", type: "Certified Quantity Surveyor (CQS)", url: "https://www.aiqs.com.au" },
    },
    standards: [
      { code: "AIQS Cost Management Manual", title: "Australian Cost Management Standards" },
      { code: "AS 4120", title: "Code of Tendering" },
      { code: "AS 4000", title: "General Conditions of Contract" },
      { code: "RICS Black Book", title: "RICS Guidance Notes for QS Practice" },
    ],
    whsNotice: "Quantity surveying services must comply with professional indemnity insurance requirements. All cost reports and bills of quantities must be prepared by or under the supervision of a Certified Quantity Surveyor (CQS) accredited by AIQS.",
    quoteDisclaimer: "This estimate is prepared by a Certified Quantity Surveyor (CQS) accredited by the Australian Institute of Quantity Surveyors (AIQS). All cost plans comply with AIQS Cost Management Manual standards. GST of 10% is included where marked. Prices are valid for 30 days from the date of issue.",
  },
  demolition: {
    licensingBodies: {
      NSW: { body: "SafeWork NSW + NSW Fair Trading", type: "Demolition Contractor Licence + High Risk Work Licence", url: "https://www.safework.nsw.gov.au/licences-and-registrations/demolition-work" },
      VIC: { body: "WorkSafe Victoria + VBA", type: "Demolition Licence + Builder's Registration", url: "https://www.worksafe.vic.gov.au/licences-and-registrations/demolition" },
      QLD: { body: "QBCC + Workplace Health and Safety QLD", type: "Builder's Licence + Demolition Work Licence", url: "https://www.qbcc.qld.gov.au" },
      SA: { body: "SafeWork SA + CBS SA", type: "Demolition Contractor Licence", url: "https://www.safework.sa.gov.au/licences-and-registrations/demolition" },
      WA: { body: "Building and Energy WA + WorkSafe WA", type: "Demolition Contractor Licence", url: "https://www.commerce.wa.gov.au/building-and-energy" },
      TAS: { body: "WorkSafe Tasmania + CBOS", type: "Demolition Contractor Licence", url: "https://worksafe.tas.gov.au" },
      NT: { body: "NT WorkSafe", type: "Demolition Contractor Licence", url: "https://worksafe.nt.gov.au" },
      ACT: { body: "WorkSafe ACT", type: "Demolition Contractor Licence", url: "https://www.worksafe.act.gov.au" },
    },
    standards: [
      { code: "AS 2601", title: "Demolition of Structures" },
      { code: "Safe Work Australia", title: "Code of Practice: Demolition Work" },
      { code: "Safe Work Australia", title: "Code of Practice: How to Manage and Control Asbestos in the Workplace" },
      { code: "AS 1726", title: "Geotechnical Site Investigations" },
    ],
    whsNotice: "Demolition work is high-risk construction work. A Safe Work Method Statement (SWMS) is mandatory. Asbestos identification and removal by a licensed asbestos removalist is required before demolition of pre-1990 structures. All workers must hold relevant high-risk work licences.",
    quoteDisclaimer: "This estimate is prepared by a licensed demolition contractor. All work will comply with AS 2601 and the Safe Work Australia Code of Practice for Demolition Work. GST of 10% is included where marked. Prices are valid for 30 days from the date of issue.",
  },
  "swimming-pool": {
    licensingBodies: {
      NSW: { body: "NSW Fair Trading", type: "Contractor Licence (Swimming Pool Building)", url: "https://www.fairtrading.nsw.gov.au/trades-and-businesses/licensing/contractor-licence" },
      VIC: { body: "Victorian Building Authority (VBA)", type: "Domestic Builder (Swimming Pool)", url: "https://www.vba.vic.gov.au/builders/registration" },
      QLD: { body: "QBCC", type: "Swimming Pool Construction, Installation and Maintenance Licence", url: "https://www.qbcc.qld.gov.au/licences/types/swimming-pool" },
      SA: { body: "Consumer and Business Services SA", type: "Building Work Contractor Licence", url: "https://www.cbs.sa.gov.au/licences/building" },
      WA: { body: "Building and Energy WA", type: "Builder's Registration", url: "https://www.commerce.wa.gov.au/building-and-energy/builders-registration" },
      TAS: { body: "CBOS Tasmania", type: "Building Practitioner Registration", url: "https://www.cbos.tas.gov.au/topics/licensing/building" },
      NT: { body: "NT Building Practitioners Board", type: "Builder's Licence", url: "https://nt.gov.au/industry/construction/licences-and-registrations/building-practitioners" },
      ACT: { body: "Access Canberra", type: "Builder's Licence", url: "https://www.accesscanberra.act.gov.au/s/article/builders-licence" },
    },
    standards: [
      { code: "AS 1926.1", title: "Swimming Pool Safety - Safety Barriers for Swimming Pools" },
      { code: "AS 1926.2", title: "Swimming Pool Safety - Location of Safety Barriers" },
      { code: "AS 3979", title: "Hydrotherapy Pools" },
      { code: "NCC Volume 2", title: "National Construction Code" },
    ],
    whsNotice: "Swimming pool construction must comply with WHS regulations. Pool safety barriers must comply with AS 1926 before the pool is filled. All electrical work associated with pool equipment must be performed by a licensed electrician. Pool fencing compliance certificate required at completion.",
    quoteDisclaimer: "This estimate is prepared by a licensed swimming pool contractor. All work will comply with AS 1926 pool safety barrier standards and the National Construction Code. GST of 10% is included where marked. Prices are valid for 30 days from the date of issue.",
  },
  "steel-fabrication": {
    licensingBodies: {
      NSW: { body: "NSW Fair Trading", type: "Contractor Licence (Metal Fabrication)", url: "https://www.fairtrading.nsw.gov.au/trades-and-businesses/licensing/contractor-licence" },
      VIC: { body: "Victorian Building Authority (VBA)", type: "Domestic Builder (Metal Fabrication)", url: "https://www.vba.vic.gov.au/builders/registration" },
      QLD: { body: "QBCC", type: "Metal Fabrication and Erection — Structural Licence", url: "https://www.qbcc.qld.gov.au/licences/types/metal-fabrication" },
      SA: { body: "Consumer and Business Services SA", type: "Building Work Contractor Licence", url: "https://www.cbs.sa.gov.au/licences/building" },
      WA: { body: "Building and Energy WA", type: "Builder's Registration", url: "https://www.commerce.wa.gov.au/building-and-energy/builders-registration" },
      TAS: { body: "CBOS Tasmania", type: "Building Practitioner Registration", url: "https://www.cbos.tas.gov.au/topics/licensing/building" },
      NT: { body: "NT Building Practitioners Board", type: "Builder's Licence", url: "https://nt.gov.au/industry/construction/licences-and-registrations/building-practitioners" },
      ACT: { body: "Access Canberra", type: "Builder's Licence", url: "https://www.accesscanberra.act.gov.au/s/article/builders-licence" },
    },
    standards: [
      { code: "AS 4100", title: "Steel Structures" },
      { code: "AS/NZS 1554", title: "Structural Steel Welding" },
      { code: "AS 1418", title: "Cranes, Hoists and Winches" },
      { code: "NCC Volume 1", title: "National Construction Code (Class 2-9 Buildings)" },
    ],
    whsNotice: "Steel fabrication and erection is high-risk construction work. A Safe Work Method Statement (SWMS) is mandatory for all structural steel erection. All welders must hold current welding qualifications. Crane and hoist operations require licensed operators. Working at heights requires fall protection systems.",
    quoteDisclaimer: "This estimate is prepared by a licensed steel fabrication and structural contractor. All work will comply with AS 4100 Steel Structures and AS/NZS 1554 Structural Steel Welding. GST of 10% is included where marked. Prices are valid for 30 days from the date of issue.",
  },
};

// ─── Default Labour Rates (Fair Work Act 2024-25) ─────────────────────────────
export const DEFAULT_LABOUR_RATES: Record<
  string,
  Array<{
    classification: string;
    baseRate: number;
    overtimeRate: number;
    saturdayRate: number;
    sundayRate: number;
    publicHolidayRate: number;
    travelAllowance: number;
    toolAllowance: number;
  }>
> = {
  electrical: [
    { classification: "Electrician - Apprentice 1st Year", baseRate: 16.50, overtimeRate: 24.75, saturdayRate: 24.75, sundayRate: 33.00, publicHolidayRate: 41.25, travelAllowance: 0, toolAllowance: 0 },
    { classification: "Electrician - Apprentice 2nd Year", baseRate: 19.80, overtimeRate: 29.70, saturdayRate: 29.70, sundayRate: 39.60, publicHolidayRate: 49.50, travelAllowance: 0, toolAllowance: 0 },
    { classification: "Electrician - Apprentice 3rd Year", baseRate: 23.10, overtimeRate: 34.65, saturdayRate: 34.65, sundayRate: 46.20, publicHolidayRate: 57.75, travelAllowance: 0, toolAllowance: 0 },
    { classification: "Electrician - Apprentice 4th Year", baseRate: 27.50, overtimeRate: 41.25, saturdayRate: 41.25, sundayRate: 55.00, publicHolidayRate: 68.75, travelAllowance: 0, toolAllowance: 0 },
    { classification: "Electrician - Qualified (Grade 5)", baseRate: 42.50, overtimeRate: 63.75, saturdayRate: 63.75, sundayRate: 85.00, publicHolidayRate: 106.25, travelAllowance: 18.50, toolAllowance: 1.80 },
    { classification: "Electrician - Advanced (Grade 6)", baseRate: 46.20, overtimeRate: 69.30, saturdayRate: 69.30, sundayRate: 92.40, publicHolidayRate: 115.50, travelAllowance: 18.50, toolAllowance: 1.80 },
    { classification: "Electrical Supervisor", baseRate: 52.00, overtimeRate: 78.00, saturdayRate: 78.00, sundayRate: 104.00, publicHolidayRate: 130.00, travelAllowance: 18.50, toolAllowance: 1.80 },
  ],
  plumbing: [
    { classification: "Plumber - Apprentice 1st Year", baseRate: 16.50, overtimeRate: 24.75, saturdayRate: 24.75, sundayRate: 33.00, publicHolidayRate: 41.25, travelAllowance: 0, toolAllowance: 0 },
    { classification: "Plumber - Apprentice 2nd Year", baseRate: 19.80, overtimeRate: 29.70, saturdayRate: 29.70, sundayRate: 39.60, publicHolidayRate: 49.50, travelAllowance: 0, toolAllowance: 0 },
    { classification: "Plumber - Apprentice 3rd Year", baseRate: 23.10, overtimeRate: 34.65, saturdayRate: 34.65, sundayRate: 46.20, publicHolidayRate: 57.75, travelAllowance: 0, toolAllowance: 0 },
    { classification: "Plumber - Apprentice 4th Year", baseRate: 27.50, overtimeRate: 41.25, saturdayRate: 41.25, sundayRate: 55.00, publicHolidayRate: 68.75, travelAllowance: 0, toolAllowance: 0 },
    { classification: "Plumber - Qualified", baseRate: 43.80, overtimeRate: 65.70, saturdayRate: 65.70, sundayRate: 87.60, publicHolidayRate: 109.50, travelAllowance: 18.50, toolAllowance: 1.80 },
    { classification: "Plumber - Advanced", baseRate: 47.50, overtimeRate: 71.25, saturdayRate: 71.25, sundayRate: 95.00, publicHolidayRate: 118.75, travelAllowance: 18.50, toolAllowance: 1.80 },
    { classification: "Plumbing Supervisor", baseRate: 54.00, overtimeRate: 81.00, saturdayRate: 81.00, sundayRate: 108.00, publicHolidayRate: 135.00, travelAllowance: 18.50, toolAllowance: 1.80 },
  ],
  carpentry: [
    { classification: "Carpenter - Apprentice 1st Year", baseRate: 15.50, overtimeRate: 23.25, saturdayRate: 23.25, sundayRate: 31.00, publicHolidayRate: 38.75, travelAllowance: 0, toolAllowance: 0 },
    { classification: "Carpenter - Apprentice 2nd Year", baseRate: 18.60, overtimeRate: 27.90, saturdayRate: 27.90, sundayRate: 37.20, publicHolidayRate: 46.50, travelAllowance: 0, toolAllowance: 0 },
    { classification: "Carpenter - Apprentice 3rd Year", baseRate: 21.70, overtimeRate: 32.55, saturdayRate: 32.55, sundayRate: 43.40, publicHolidayRate: 54.25, travelAllowance: 0, toolAllowance: 0 },
    { classification: "Carpenter - Apprentice 4th Year", baseRate: 25.80, overtimeRate: 38.70, saturdayRate: 38.70, sundayRate: 51.60, publicHolidayRate: 64.50, travelAllowance: 0, toolAllowance: 0 },
    { classification: "Carpenter - Qualified (CW3)", baseRate: 38.50, overtimeRate: 57.75, saturdayRate: 57.75, sundayRate: 77.00, publicHolidayRate: 96.25, travelAllowance: 17.50, toolAllowance: 1.60 },
    { classification: "Carpenter - Advanced (CW4)", baseRate: 42.00, overtimeRate: 63.00, saturdayRate: 63.00, sundayRate: 84.00, publicHolidayRate: 105.00, travelAllowance: 17.50, toolAllowance: 1.60 },
    { classification: "Carpentry Supervisor", baseRate: 48.00, overtimeRate: 72.00, saturdayRate: 72.00, sundayRate: 96.00, publicHolidayRate: 120.00, travelAllowance: 17.50, toolAllowance: 1.60 },
  ],
  concreting: [
    { classification: "Concrete Worker - Grade 1", baseRate: 30.00, overtimeRate: 45.00, saturdayRate: 45.00, sundayRate: 60.00, publicHolidayRate: 75.00, travelAllowance: 16.00, toolAllowance: 0 },
    { classification: "Concrete Worker - Grade 2", baseRate: 33.50, overtimeRate: 50.25, saturdayRate: 50.25, sundayRate: 67.00, publicHolidayRate: 83.75, travelAllowance: 16.00, toolAllowance: 0 },
    { classification: "Concrete Finisher", baseRate: 38.00, overtimeRate: 57.00, saturdayRate: 57.00, sundayRate: 76.00, publicHolidayRate: 95.00, travelAllowance: 16.00, toolAllowance: 0 },
    { classification: "Concreting Supervisor", baseRate: 46.00, overtimeRate: 69.00, saturdayRate: 69.00, sundayRate: 92.00, publicHolidayRate: 115.00, travelAllowance: 16.00, toolAllowance: 0 },
  ],
  hvac: [
    { classification: "HVAC Technician - Apprentice 1st Year", baseRate: 16.00, overtimeRate: 24.00, saturdayRate: 24.00, sundayRate: 32.00, publicHolidayRate: 40.00, travelAllowance: 0, toolAllowance: 0 },
    { classification: "HVAC Technician - Apprentice 2nd Year", baseRate: 19.20, overtimeRate: 28.80, saturdayRate: 28.80, sundayRate: 38.40, publicHolidayRate: 48.00, travelAllowance: 0, toolAllowance: 0 },
    { classification: "HVAC Technician - Qualified", baseRate: 44.00, overtimeRate: 66.00, saturdayRate: 66.00, sundayRate: 88.00, publicHolidayRate: 110.00, travelAllowance: 18.50, toolAllowance: 1.80 },
    { classification: "HVAC Technician - Advanced", baseRate: 48.50, overtimeRate: 72.75, saturdayRate: 72.75, sundayRate: 97.00, publicHolidayRate: 121.25, travelAllowance: 18.50, toolAllowance: 1.80 },
    { classification: "HVAC Supervisor", baseRate: 55.00, overtimeRate: 82.50, saturdayRate: 82.50, sundayRate: 110.00, publicHolidayRate: 137.50, travelAllowance: 18.50, toolAllowance: 1.80 },
  ],
  flooring: [
    { classification: "Floor Layer - Grade 1", baseRate: 30.00, overtimeRate: 45.00, saturdayRate: 45.00, sundayRate: 60.00, publicHolidayRate: 75.00, travelAllowance: 16.00, toolAllowance: 1.20 },
    { classification: "Floor Layer - Grade 2", baseRate: 34.00, overtimeRate: 51.00, saturdayRate: 51.00, sundayRate: 68.00, publicHolidayRate: 85.00, travelAllowance: 16.00, toolAllowance: 1.20 },
    { classification: "Floor Layer - Qualified", baseRate: 38.50, overtimeRate: 57.75, saturdayRate: 57.75, sundayRate: 77.00, publicHolidayRate: 96.25, travelAllowance: 16.00, toolAllowance: 1.20 },
    { classification: "Flooring Supervisor", baseRate: 46.00, overtimeRate: 69.00, saturdayRate: 69.00, sundayRate: 92.00, publicHolidayRate: 115.00, travelAllowance: 16.00, toolAllowance: 1.20 },
  ],
  landscaping: [
    { classification: "Landscape Labourer", baseRate: 28.00, overtimeRate: 42.00, saturdayRate: 42.00, sundayRate: 56.00, publicHolidayRate: 70.00, travelAllowance: 14.00, toolAllowance: 0 },
    { classification: "Landscape Gardener - Grade 1", baseRate: 32.00, overtimeRate: 48.00, saturdayRate: 48.00, sundayRate: 64.00, publicHolidayRate: 80.00, travelAllowance: 14.00, toolAllowance: 0 },
    { classification: "Landscape Gardener - Qualified", baseRate: 37.50, overtimeRate: 56.25, saturdayRate: 56.25, sundayRate: 75.00, publicHolidayRate: 93.75, travelAllowance: 14.00, toolAllowance: 0 },
    { classification: "Landscape Supervisor", baseRate: 45.00, overtimeRate: 67.50, saturdayRate: 67.50, sundayRate: 90.00, publicHolidayRate: 112.50, travelAllowance: 14.00, toolAllowance: 0 },
  ],
  cabinetry: [
    { classification: "Cabinet Maker - Apprentice 1st Year", baseRate: 15.00, overtimeRate: 22.50, saturdayRate: 22.50, sundayRate: 30.00, publicHolidayRate: 37.50, travelAllowance: 0, toolAllowance: 0 },
    { classification: "Cabinet Maker - Apprentice 2nd Year", baseRate: 18.00, overtimeRate: 27.00, saturdayRate: 27.00, sundayRate: 36.00, publicHolidayRate: 45.00, travelAllowance: 0, toolAllowance: 0 },
    { classification: "Cabinet Maker - Qualified", baseRate: 38.00, overtimeRate: 57.00, saturdayRate: 57.00, sundayRate: 76.00, publicHolidayRate: 95.00, travelAllowance: 16.00, toolAllowance: 1.50 },
    { classification: "Cabinet Maker - Advanced", baseRate: 42.50, overtimeRate: 63.75, saturdayRate: 63.75, sundayRate: 85.00, publicHolidayRate: 106.25, travelAllowance: 16.00, toolAllowance: 1.50 },
    { classification: "Joinery Supervisor", baseRate: 50.00, overtimeRate: 75.00, saturdayRate: 75.00, sundayRate: 100.00, publicHolidayRate: 125.00, travelAllowance: 16.00, toolAllowance: 1.50 },
  ],
  rendering: [
    { classification: "Plasterer - Apprentice 1st Year", baseRate: 15.50, overtimeRate: 23.25, saturdayRate: 23.25, sundayRate: 31.00, publicHolidayRate: 38.75, travelAllowance: 0, toolAllowance: 0 },
    { classification: "Plasterer - Apprentice 2nd Year", baseRate: 18.60, overtimeRate: 27.90, saturdayRate: 27.90, sundayRate: 37.20, publicHolidayRate: 46.50, travelAllowance: 0, toolAllowance: 0 },
    { classification: "Plasterer - Qualified", baseRate: 39.00, overtimeRate: 58.50, saturdayRate: 58.50, sundayRate: 78.00, publicHolidayRate: 97.50, travelAllowance: 17.00, toolAllowance: 1.40 },
    { classification: "Plasterer - Advanced", baseRate: 43.00, overtimeRate: 64.50, saturdayRate: 64.50, sundayRate: 86.00, publicHolidayRate: 107.50, travelAllowance: 17.00, toolAllowance: 1.40 },
    { classification: "Plastering Supervisor", baseRate: 50.00, overtimeRate: 75.00, saturdayRate: 75.00, sundayRate: 100.00, publicHolidayRate: 125.00, travelAllowance: 17.00, toolAllowance: 1.40 },
  ],
  painting: [
    { classification: "Painter - Apprentice 1st Year", baseRate: 15.00, overtimeRate: 22.50, saturdayRate: 22.50, sundayRate: 30.00, publicHolidayRate: 37.50, travelAllowance: 0, toolAllowance: 0 },
    { classification: "Painter - Apprentice 2nd Year", baseRate: 18.00, overtimeRate: 27.00, saturdayRate: 27.00, sundayRate: 36.00, publicHolidayRate: 45.00, travelAllowance: 0, toolAllowance: 0 },
    { classification: "Painter - Apprentice 3rd Year", baseRate: 21.00, overtimeRate: 31.50, saturdayRate: 31.50, sundayRate: 42.00, publicHolidayRate: 52.50, travelAllowance: 0, toolAllowance: 0 },
    { classification: "Painter - Qualified", baseRate: 36.50, overtimeRate: 54.75, saturdayRate: 54.75, sundayRate: 73.00, publicHolidayRate: 91.25, travelAllowance: 16.50, toolAllowance: 1.20 },
    { classification: "Painter - Advanced", baseRate: 40.00, overtimeRate: 60.00, saturdayRate: 60.00, sundayRate: 80.00, publicHolidayRate: 100.00, travelAllowance: 16.50, toolAllowance: 1.20 },
    { classification: "Painting Supervisor", baseRate: 47.00, overtimeRate: 70.50, saturdayRate: 70.50, sundayRate: 94.00, publicHolidayRate: 117.50, travelAllowance: 16.50, toolAllowance: 1.20 },
  ],
  bricklaying: [
    { classification: "Bricklayer - Apprentice 1st Year", baseRate: 15.50, overtimeRate: 23.25, saturdayRate: 23.25, sundayRate: 31.00, publicHolidayRate: 38.75, travelAllowance: 0, toolAllowance: 0 },
    { classification: "Bricklayer - Apprentice 2nd Year", baseRate: 18.60, overtimeRate: 27.90, saturdayRate: 27.90, sundayRate: 37.20, publicHolidayRate: 46.50, travelAllowance: 0, toolAllowance: 0 },
    { classification: "Bricklayer - Qualified", baseRate: 40.00, overtimeRate: 60.00, saturdayRate: 60.00, sundayRate: 80.00, publicHolidayRate: 100.00, travelAllowance: 17.50, toolAllowance: 1.50 },
    { classification: "Bricklayer - Advanced", baseRate: 44.00, overtimeRate: 66.00, saturdayRate: 66.00, sundayRate: 88.00, publicHolidayRate: 110.00, travelAllowance: 17.50, toolAllowance: 1.50 },
    { classification: "Bricklaying Supervisor", baseRate: 51.00, overtimeRate: 76.50, saturdayRate: 76.50, sundayRate: 102.00, publicHolidayRate: 127.50, travelAllowance: 17.50, toolAllowance: 1.50 },
  ],
  roofing: [
    { classification: "Roof Tiler - Apprentice 1st Year", baseRate: 15.50, overtimeRate: 23.25, saturdayRate: 23.25, sundayRate: 31.00, publicHolidayRate: 38.75, travelAllowance: 0, toolAllowance: 0 },
    { classification: "Roof Tiler - Apprentice 2nd Year", baseRate: 18.60, overtimeRate: 27.90, saturdayRate: 27.90, sundayRate: 37.20, publicHolidayRate: 46.50, travelAllowance: 0, toolAllowance: 0 },
    { classification: "Roof Tiler - Qualified", baseRate: 41.00, overtimeRate: 61.50, saturdayRate: 61.50, sundayRate: 82.00, publicHolidayRate: 102.50, travelAllowance: 18.00, toolAllowance: 1.60 },
    { classification: "Roof Plumber - Qualified", baseRate: 44.00, overtimeRate: 66.00, saturdayRate: 66.00, sundayRate: 88.00, publicHolidayRate: 110.00, travelAllowance: 18.50, toolAllowance: 1.80 },
    { classification: "Roofing Supervisor", baseRate: 52.00, overtimeRate: 78.00, saturdayRate: 78.00, sundayRate: 104.00, publicHolidayRate: 130.00, travelAllowance: 18.00, toolAllowance: 1.60 },
  ],
  tiling: [
    { classification: "Tiler - Apprentice 1st Year", baseRate: 15.00, overtimeRate: 22.50, saturdayRate: 22.50, sundayRate: 30.00, publicHolidayRate: 37.50, travelAllowance: 0, toolAllowance: 0 },
    { classification: "Tiler - Apprentice 2nd Year", baseRate: 18.00, overtimeRate: 27.00, saturdayRate: 27.00, sundayRate: 36.00, publicHolidayRate: 45.00, travelAllowance: 0, toolAllowance: 0 },
    { classification: "Tiler - Qualified", baseRate: 38.00, overtimeRate: 57.00, saturdayRate: 57.00, sundayRate: 76.00, publicHolidayRate: 95.00, travelAllowance: 16.50, toolAllowance: 1.40 },
    { classification: "Tiler - Advanced", baseRate: 42.00, overtimeRate: 63.00, saturdayRate: 63.00, sundayRate: 84.00, publicHolidayRate: 105.00, travelAllowance: 16.50, toolAllowance: 1.40 },
    { classification: "Tiling Supervisor", baseRate: 49.00, overtimeRate: 73.50, saturdayRate: 73.50, sundayRate: 98.00, publicHolidayRate: 122.50, travelAllowance: 16.50, toolAllowance: 1.40 },
  ],
  waterproofing: [
    { classification: "Waterproofer - Grade 1", baseRate: 32.00, overtimeRate: 48.00, saturdayRate: 48.00, sundayRate: 64.00, publicHolidayRate: 80.00, travelAllowance: 16.00, toolAllowance: 1.20 },
    { classification: "Waterproofer - Qualified", baseRate: 40.00, overtimeRate: 60.00, saturdayRate: 60.00, sundayRate: 80.00, publicHolidayRate: 100.00, travelAllowance: 16.00, toolAllowance: 1.20 },
    { classification: "Waterproofer - Advanced", baseRate: 45.00, overtimeRate: 67.50, saturdayRate: 67.50, sundayRate: 90.00, publicHolidayRate: 112.50, travelAllowance: 16.00, toolAllowance: 1.20 },
    { classification: "Waterproofing Supervisor", baseRate: 52.00, overtimeRate: 78.00, saturdayRate: 78.00, sundayRate: 104.00, publicHolidayRate: 130.00, travelAllowance: 16.00, toolAllowance: 1.20 },
  ],
  "fire-protection": [
    { classification: "Fire Protection Technician - Grade 1", baseRate: 34.00, overtimeRate: 51.00, saturdayRate: 51.00, sundayRate: 68.00, publicHolidayRate: 85.00, travelAllowance: 18.00, toolAllowance: 1.60 },
    { classification: "Fire Protection Technician - Qualified", baseRate: 46.00, overtimeRate: 69.00, saturdayRate: 69.00, sundayRate: 92.00, publicHolidayRate: 115.00, travelAllowance: 18.00, toolAllowance: 1.60 },
    { classification: "Fire Protection Engineer", baseRate: 65.00, overtimeRate: 97.50, saturdayRate: 97.50, sundayRate: 130.00, publicHolidayRate: 162.50, travelAllowance: 18.00, toolAllowance: 1.60 },
    { classification: "Fire Protection Supervisor", baseRate: 58.00, overtimeRate: 87.00, saturdayRate: 87.00, sundayRate: 116.00, publicHolidayRate: 145.00, travelAllowance: 18.00, toolAllowance: 1.60 },
  ],
  glazing: [
    { classification: "Glazier - Apprentice 1st Year", baseRate: 15.50, overtimeRate: 23.25, saturdayRate: 23.25, sundayRate: 31.00, publicHolidayRate: 38.75, travelAllowance: 0, toolAllowance: 0 },
    { classification: "Glazier - Apprentice 2nd Year", baseRate: 18.60, overtimeRate: 27.90, saturdayRate: 27.90, sundayRate: 37.20, publicHolidayRate: 46.50, travelAllowance: 0, toolAllowance: 0 },
    { classification: "Glazier - Qualified", baseRate: 40.00, overtimeRate: 60.00, saturdayRate: 60.00, sundayRate: 80.00, publicHolidayRate: 100.00, travelAllowance: 17.50, toolAllowance: 1.50 },
    { classification: "Glazier - Advanced", baseRate: 44.00, overtimeRate: 66.00, saturdayRate: 66.00, sundayRate: 88.00, publicHolidayRate: 110.00, travelAllowance: 17.50, toolAllowance: 1.50 },
    { classification: "Glazing Supervisor", baseRate: 52.00, overtimeRate: 78.00, saturdayRate: 78.00, sundayRate: 104.00, publicHolidayRate: 130.00, travelAllowance: 17.50, toolAllowance: 1.50 },
  ],
  "quantity-surveying": [
    { classification: "Graduate Quantity Surveyor", baseRate: 45.00, overtimeRate: 67.50, saturdayRate: 67.50, sundayRate: 90.00, publicHolidayRate: 112.50, travelAllowance: 0, toolAllowance: 0 },
    { classification: "Quantity Surveyor - Intermediate", baseRate: 60.00, overtimeRate: 90.00, saturdayRate: 90.00, sundayRate: 120.00, publicHolidayRate: 150.00, travelAllowance: 0, toolAllowance: 0 },
    { classification: "Senior Quantity Surveyor", baseRate: 80.00, overtimeRate: 120.00, saturdayRate: 120.00, sundayRate: 160.00, publicHolidayRate: 200.00, travelAllowance: 0, toolAllowance: 0 },
    { classification: "Principal / Associate QS", baseRate: 110.00, overtimeRate: 165.00, saturdayRate: 165.00, sundayRate: 220.00, publicHolidayRate: 275.00, travelAllowance: 0, toolAllowance: 0 },
  ],
  demolition: [
    { classification: "Demolition Labourer", baseRate: 32.00, overtimeRate: 48.00, saturdayRate: 48.00, sundayRate: 64.00, publicHolidayRate: 80.00, travelAllowance: 16.00, toolAllowance: 0 },
    { classification: "Demolition Worker - Qualified", baseRate: 42.00, overtimeRate: 63.00, saturdayRate: 63.00, sundayRate: 84.00, publicHolidayRate: 105.00, travelAllowance: 16.00, toolAllowance: 0 },
    { classification: "Excavator Operator", baseRate: 46.00, overtimeRate: 69.00, saturdayRate: 69.00, sundayRate: 92.00, publicHolidayRate: 115.00, travelAllowance: 16.00, toolAllowance: 0 },
    { classification: "Demolition Supervisor", baseRate: 55.00, overtimeRate: 82.50, saturdayRate: 82.50, sundayRate: 110.00, publicHolidayRate: 137.50, travelAllowance: 16.00, toolAllowance: 0 },
  ],
  "swimming-pool": [
    { classification: "Pool Labourer", baseRate: 30.00, overtimeRate: 45.00, saturdayRate: 45.00, sundayRate: 60.00, publicHolidayRate: 75.00, travelAllowance: 16.00, toolAllowance: 0 },
    { classification: "Pool Builder - Qualified", baseRate: 44.00, overtimeRate: 66.00, saturdayRate: 66.00, sundayRate: 88.00, publicHolidayRate: 110.00, travelAllowance: 16.00, toolAllowance: 1.40 },
    { classification: "Pool Technician - Equipment", baseRate: 46.00, overtimeRate: 69.00, saturdayRate: 69.00, sundayRate: 92.00, publicHolidayRate: 115.00, travelAllowance: 16.00, toolAllowance: 1.40 },
    { classification: "Pool Supervisor", baseRate: 54.00, overtimeRate: 81.00, saturdayRate: 81.00, sundayRate: 108.00, publicHolidayRate: 135.00, travelAllowance: 16.00, toolAllowance: 1.40 },
  ],
  "steel-fabrication": [
    { classification: "Steel Fixer - Grade 1", baseRate: 34.00, overtimeRate: 51.00, saturdayRate: 51.00, sundayRate: 68.00, publicHolidayRate: 85.00, travelAllowance: 17.00, toolAllowance: 1.40 },
    { classification: "Boilermaker / Welder - Qualified", baseRate: 46.00, overtimeRate: 69.00, saturdayRate: 69.00, sundayRate: 92.00, publicHolidayRate: 115.00, travelAllowance: 17.00, toolAllowance: 1.80 },
    { classification: "Structural Steel Erector", baseRate: 52.00, overtimeRate: 78.00, saturdayRate: 78.00, sundayRate: 104.00, publicHolidayRate: 130.00, travelAllowance: 17.00, toolAllowance: 1.80 },
    { classification: "Steel Fabrication Supervisor", baseRate: 62.00, overtimeRate: 93.00, saturdayRate: 93.00, sundayRate: 124.00, publicHolidayRate: 155.00, travelAllowance: 17.00, toolAllowance: 1.80 },
  ],
  gasfitting: [
    { classification: "Gasfitter - Apprentice 1st Year", baseRate: 16.50, overtimeRate: 24.75, saturdayRate: 24.75, sundayRate: 33.00, publicHolidayRate: 41.25, travelAllowance: 0, toolAllowance: 0 },
    { classification: "Gasfitter - Apprentice 4th Year", baseRate: 28.00, overtimeRate: 42.00, saturdayRate: 42.00, sundayRate: 56.00, publicHolidayRate: 70.00, travelAllowance: 16.00, toolAllowance: 1.40 },
    { classification: "Gasfitter - Qualified (CPC32420)", baseRate: 48.00, overtimeRate: 72.00, saturdayRate: 72.00, sundayRate: 96.00, publicHolidayRate: 120.00, travelAllowance: 17.00, toolAllowance: 1.80 },
    { classification: "Gas Service Technician", baseRate: 48.00, overtimeRate: 72.00, saturdayRate: 72.00, sundayRate: 96.00, publicHolidayRate: 120.00, travelAllowance: 17.00, toolAllowance: 1.80 },
    { classification: "Gasfitter - Leading Hand", baseRate: 54.00, overtimeRate: 81.00, saturdayRate: 81.00, sundayRate: 108.00, publicHolidayRate: 135.00, travelAllowance: 17.00, toolAllowance: 1.80 },
    { classification: "Gas Compliance Inspector", baseRate: 58.00, overtimeRate: 87.00, saturdayRate: 87.00, sundayRate: 116.00, publicHolidayRate: 145.00, travelAllowance: 17.00, toolAllowance: 1.80 },
    { classification: "Gasfitter - Contractor/Supervisor", baseRate: 65.00, overtimeRate: 97.50, saturdayRate: 97.50, sundayRate: 130.00, publicHolidayRate: 162.50, travelAllowance: 17.00, toolAllowance: 1.80 },
  ],
};
